// Known Slack Web API methods available to bot tokens.
// This list is used for the list-methods command and help text.
// The CLI is not limited to these — any method string is passed to apiCall().
export const KNOWN_METHODS = [
  'api.test',
  'assistant.threads.setStatus',
  'assistant.threads.setSuggestedPrompts',
  'assistant.threads.setTitle',
  'auth.revoke',
  'auth.teams.list',
  'auth.test',
  'bookmarks.add',
  'bookmarks.edit',
  'bookmarks.list',
  'bookmarks.remove',
  'bots.info',
  'calls.add',
  'calls.end',
  'calls.info',
  'calls.participants.add',
  'calls.participants.remove',
  'calls.update',
  'canvases.access.delete',
  'canvases.access.set',
  'canvases.create',
  'canvases.delete',
  'canvases.edit',
  'canvases.sections.lookup',
  'chat.delete',
  'chat.deleteScheduledMessage',
  'chat.getPermalink',
  'chat.meMessage',
  'chat.postEphemeral',
  'chat.postMessage',
  'chat.scheduleMessage',
  'chat.scheduledMessages.list',
  'chat.unfurl',
  'chat.update',
  'conversations.acceptSharedInvite',
  'conversations.approveSharedInvite',
  'conversations.archive',
  'conversations.canvases.create',
  'conversations.close',
  'conversations.create',
  'conversations.declineSharedInvite',
  'conversations.history',
  'conversations.info',
  'conversations.invite',
  'conversations.inviteShared',
  'conversations.join',
  'conversations.kick',
  'conversations.leave',
  'conversations.list',
  'conversations.listConnectInvites',
  'conversations.mark',
  'conversations.members',
  'conversations.open',
  'conversations.rename',
  'conversations.replies',
  'conversations.setPurpose',
  'conversations.setTopic',
  'conversations.unarchive',
  'dialog.open',
  'dnd.endDnd',
  'dnd.endSnooze',
  'dnd.info',
  'dnd.setSnooze',
  'dnd.teamInfo',
  'emoji.list',
  'files.completeUploadExternal',
  'files.comments.delete',
  'files.delete',
  'files.getUploadURLExternal',
  'files.info',
  'files.list',
  'files.remote.add',
  'files.remote.info',
  'files.remote.list',
  'files.remote.remove',
  'files.remote.share',
  'files.remote.update',
  'files.revokePublicURL',
  'files.sharedPublicURL',
  'files.upload',
  'migration.exchange',
  'pins.add',
  'pins.list',
  'pins.remove',
  'reactions.add',
  'reactions.get',
  'reactions.list',
  'reactions.remove',
  'reminders.add',
  'reminders.complete',
  'reminders.delete',
  'reminders.info',
  'reminders.list',
  'team.accessLogs',
  'team.billableInfo',
  'team.info',
  'team.integrationLogs',
  'team.profile.get',
  'usergroups.create',
  'usergroups.disable',
  'usergroups.enable',
  'usergroups.list',
  'usergroups.update',
  'usergroups.users.list',
  'usergroups.users.update',
  'users.conversations',
  'users.getPresence',
  'users.info',
  'users.list',
  'users.lookupByEmail',
  'users.profile.get',
  'users.setPresence',
  'views.open',
  'views.publish',
  'views.push',
  'views.update',
  'workflows.stepCompleted',
  'workflows.stepFailed',
  'workflows.updateStep',
];

// CLI convenience methods that are not part of the Slack Web API. They are
// tracked separately from KNOWN_METHODS so discovery (list-methods, describe)
// and unknown-method warnings recognize them. files.download works in both
// transports: direct mode reads url_private_download from files.info and
// fetches it with the bot token; proxy mode delegates to the broker.
export const CLI_METHODS = [
  'files.download',
];

export function isKnownMethod(method: string): boolean {
  return KNOWN_METHODS.includes(method) || CLI_METHODS.includes(method);
}
